apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: as2o33khb-go 
  janus-idp.io/tekton: as2o33khb-go
  backstage.io/kubernetes-id: as2o33khb-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: as2o33khb-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml